### ISSUE TITLE
TODO: Rework Cockpit model

### ISSUE THREAD

**Issue by merspieler** [JMaverick16/Airbus_A330#18]
Based on the discussion of #16 .

Parts of the Cockpit layout and geometry got ported from the A320 and doesn't match any A330 model.

Task is to remodel the Cockpit according to the A330.

We don't have to account for every variant but it should at least be recognizable to be an A330 cockpit.

**Comment by Kasluk24** [comment]
I would like to help, but I don't have enough time at the moment.

So I start here with a list of what should/can be done, then it's easier to work on it later
- [ ] Landing Gear Panel
- [ ] Parking Brake
- [ ] Right and left side of the glareshield
- [ ] PFD, ND XFR and brightness knobs
- [ ] Overhead, Console, Map lighting knobs

**Comment by Kasluk24** [comment]
Does anyone know how exactly the scale on the A330 trim wheel looks like? I have only found pictures of the range 0 to UP 8 and have no idea how the scale goes on (upwards and downwards).

**Comment by legoboyvdlp** [comment]
I looked in the documents but I'm afraid was unable to find it.

**Comment by Kasluk24** [comment]
Thanks for looking it up. Then I'll leave it as it is for now.

**Comment by owenexplorerph** [comment]
A good suggestion is to watch some A330 CBT videos so that the cockpit and system modelling is close to true accuracy. The YouTube playlist from Anson Aviation Production is a good one to check it out...
https://www.youtube.com/playlist?list=PL_4ljWrVvM90dTZLUa6dxtjzG2zUD3Kxg

**Comment by FurryMLG** [comment]
][https://ccntservice.airbus.com/apps/cockpits/a330/?_ga=2.245922180.1697787185.1633938490-1881885065.1633679760](url)
Well dunno if this is necroposting but here's a good reference image- from airbus official website.

**Comment by merspieler** [comment]
This is far from complete and still an outstanding task.
Just cause no one is working on it rn doesn't mean, it's not an issue anymore

**Comment by Octal450** [comment]
Guess I didn't read it enough. It's been to long. I doubt anyone will work on it until I restart development, ok we can leave this open.
